# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'presensi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3, sys
from sqlite3 import Error
import numpy as np
import cv2

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(738, 399)
        self.txpresensi = QtWidgets.QTextEdit(Dialog)
        self.txpresensi.setGeometry(QtCore.QRect(-20, 0, 761, 81))
        self.txpresensi.setStyleSheet("background-color: rgb(0, 0, 91);\n"
"border-color: rgb(0, 0, 91);")
        self.txpresensi.setObjectName("txpresensi")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 80, 741, 321))
        self.textEdit_2.setStyleSheet("background-color: rgb(57, 146, 255);\n"
"background-color: rgb(60, 138, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.lbnama = QtWidgets.QLabel(Dialog)
        self.lbnama.setGeometry(QtCore.QRect(310, 140, 131, 31))
        self.lbnama.setStyleSheet("color: rgb(0, 0, 91);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.lbnama.setObjectName("lbnama")
        self.lbjabatan = QtWidgets.QLabel(Dialog)
        self.lbjabatan.setGeometry(QtCore.QRect(340, 220, 71, 31))
        self.lbjabatan.setStyleSheet("color: rgb(0, 0, 91);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.lbjabatan.setObjectName("lbjabatan")
        self.pbhadir = QtWidgets.QPushButton(Dialog)
        self.pbhadir.setGeometry(QtCore.QRect(300, 300, 151, 61))
        self.pbhadir.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"font: 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pbhadir.setObjectName("pbhadir")
        self.textEdit_5 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_5.setGeometry(QtCore.QRect(0, 390, 741, 31))
        self.textEdit_5.setStyleSheet("background-color: rgb(0, 0, 91);")
        self.textEdit_5.setObjectName("textEdit_5")
        self.lbisinama = QtWidgets.QLabel(Dialog)
        self.lbisinama.setGeometry(QtCore.QRect(210, 170, 331, 31))
        self.lbisinama.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 91);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.lbisinama.setText("")
        self.lbisinama.setObjectName("lbisinama")
        self.lbisijabatan = QtWidgets.QLabel(Dialog)
        self.lbisijabatan.setGeometry(QtCore.QRect(210, 250, 331, 31))
        self.lbisijabatan.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 91);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.lbisijabatan.setText("")
        self.lbisijabatan.setObjectName("lbisijabatan")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.txpresensi.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; color:#ffffff;\">PRESENSI KARYAWAN</span></p></body></html>"))
        self.lbnama.setText(_translate("Dialog", "Nama Lengkap"))
        self.lbjabatan.setText(_translate("Dialog", "Jabatan"))
        self.pbhadir.setText(_translate("Dialog", "HADIR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
